### ISSUE TITLE
Etapa 1 - Escrever sessão "Estado da arte"

### ISSUE THREAD

**Issue by AlexPantolfo** [ICEI-PUC-Minas-PMV-SI/pmv-si-2024-1-pe7-t1-saude#16]

**Comment by Jenniferandreia** [comment]
Dificuldade: 
Questão 3 : dificuldades para apresentar os métodos de avaliações . Quais os métodos devemos usar ? 
Questão 4 : informações são relacionadas a questão 3?

**Comment by simonetec** [comment]
Enumeramos o Estado da arte em 5 itens. Encontramos dificuldade no item 3 (sobre quais abordagens/algoritmos foram utilizados) Solicitamos um help tb no item 4, concordam com as métricas?
